#+TITLE: Config
#+PROPERTY: header-args :tangle yes

#+BEGIN_SRC
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC

* Table of Contents
- [[#basics][Basics]]
  - [[#general][General]]
  - [[#line-numbering][Line Numbering]]
  - [[#theming][Theming]]
    - [[#transparency][Transparency]]
    - [[#font-stuff][Font Stuff]]
  - [[#org-mode][Org-Mode]]
    - [[#syntax-highlighting][Syntax Highlighting]]
- [[#company][Company]]
    - [[#org---latex-export-präambel][Org -> Latex Export Präambel]]
- [[#latex-setup][latex setup]]
- [[#smartparens-setup][Smartparens Setup]]


* Basics

** General

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.
#+BEGIN_SRC elisp

(setq user-full-name "John Doe"
      user-mail-address "john@doe.com")

      #+END_SRC


Which Key Popup Time
#+BEGIN_SRC elisp

(after! which-key
  (setq which-key-idle-delay 0.1))

#+END_SRC


Beacon Mode (Cursor blinking)
#+BEGIN_SRC elisp

(setq beacon-mode 1)

#+END_SRC

** Line Numbering

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC elisp
(setq display-line-numbers-type 'relative)
#+END_SRC

** Theming

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+BEGIN_SRC elisp

(setq doom-theme 'doom-gruvbox)

#+END_SRC

*** Transparency

#+BEGIN_SRC elisp

(set-frame-parameter (selected-frame) 'alpha '(92 100))

(add-to-list 'default-frame-alist '(alpha 95 100))

#+END_SRC

*** Font Stuff

Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

- `doom-font'
- `doom-variable-pitch-font'
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:

#+BEGIN_SRC elisp

(setq doom-font (font-spec :family "Iosevka" :size 22 :weight 'normal)
      doom-variable-pitch-font (font-spec :family "sans" :size 13))

#+END_SRC

** Org-Mode

Org-Ref import
#+BEGIN_SRC elisp

(require 'org-ref)

#+END_SRC

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!
#+BEGIN_SRC elisp

(setq org-directory "~/org/")

#+END_SRC

Changing bullet style
#+BEGIN_SRC elisp

(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))

#+END_SRC


Hide the emphasis markup (e.g. /.../ for italics, *...* for bold, etc.):
#+BEGIN_SRC elisp

(setq org-hide-emphasis-markers t)

#+END_SRC

List item marker
#+BEGIN_SRC elisp

(font-lock-add-keywords 'org-mode
                        '(("^ *\\([-]\\) "
                           (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

#+END_SRC



*** Syntax Highlighting

Fontify code in code blocks
#+BEGIN_SRC elisp

(setq org-src-fontify-natively t)

#+END_SRC



* Company


#+BEGIN_SRC elisp

(setq company-idle-delay 0.2
      company-minimum-prefix-length 3)

(after! latex
  (set-company-backend! 'latex-mode '(company-yasnippet)))

#+END_SRC

*** Org -> Latex Export Präambel

My custom LaTeX class for Org-mode export. require is needed for it to work.
#+BEGIN_SRC elisp

(unless (boundp 'org-latex-classes)
  (setq org-latex-classes nil))

(add-to-list 'org-latex-classes
             '("myclass"
               "
                \\documentclass[12pt]{scrartcl}
                \\linespread{1.15}
[NO-DEFAULT-PACKAGES]
      [PACKAGES]
\\usepackage[ngerman]{babel}
\\usepackage[utf8]{inputenc}
\\usepackage{csquotes}
\\usepackage{amssymb,amsmath, amsthm, mathtools, mathrsfs}
\\usepackage{my_macros}
\\usepackage[backend= biber]{biblatex}

\\usepackage{scrlayer-scrpage}
\\ohead{Weber, Marcus}
\\ihead{Holzer, Yannik}


\\usepackage{float}
\\usepackage{caption}
\\captionsetup[figure]{labelfont={bf},name={Abbildung},labelsep=period}
\\captionsetup[table]{labelfont={bf},name={Tabelle},labelsep=period}
\\usepackage{hyperref}
\\usepackage{graphicx}
\\usepackage{geometry}
\\geometry{
 a4paper,
 left=25mm,
 right=25mm,
 top=25mm,
 bottom=20m}
\\usepackage{cleveref}
\\addto\\captionsngerman{
  \\crefname{figure}{Abb.}{Abb.}
  \\Crefname{figure}{Abbildung}{Abbildungen}
  \\crefname{table}{Tab.}{Tab.}
  \\crefname{equation}{Gl.}{Gl.}
\\setlength\\parindent{0pt}
\\usepackage{lmodern}
      [EXTRA]
\\linespread{1.1}
\\hypersetup{pdfborder=0 0 0}"
("\\section{%s}" . "\\section*{%s}")
("\\subsection{%s}" . "\\subsection*{%s}")
("\\subsubsection{%s}" . "\\subsubsection*{%s}")
("\\paragraph{%s}" . "\\paragraph*{%s}
                "
               )))

#+END_SRC


* latex setup

#+BEGIN_SRC elisp

(setq tab-width 4
        LaTeX-item-indent 0 latex "latex"
        TeX-view-program-selection '((output-pdf "PDF Tools"))
        TeX-view-program-list
        '(("PDF Tools" TeX-pdf-tools-sync-view)))
(add-hook
   'TeX-after-compilation-finished-hook
   #'TeX-revert-document-buffer)


(setq-default TeX-parse-self t)
(setq-default TeX-auto-save t)
(setq +latex-viewers '(pdf-tools))

#+END_SRC


Auto indent with RET (you don't need to constantly press TAB to get your indentation right).

#+BEGIN_SRC elisp

(add-hook 'TeX-mode-hook
          '(lambda () (local-set-key (kbd "RET") 'newline-and-indent)))

(add-hook 'LaTeX-mode-hook 'add-my-latex-environments)
(defun add-my-latex-environments ()
  (LaTeX-add-environments
   '("DispWithArrows*" LaTeX-env-label)
   '("arrowEquation" LaTeX-env-label)))

#+END_SRC


Code I added to make syntax highlighting work in Auctex
#+BEGIN_SRC elisp

(custom-set-variables
 '(font-latex-math-environments (quote
     ("display" "displaymath" "equation" "eqnarray" "gather" "multline"
      "align" "alignat" "xalignat" "dmath" "arrowEquation" "DispWithArrows*")))
 '(TeX-insert-braces nil)
 '(texmathp-tex-commands (quote (("arrowEquation" env-on) ("DispWithArrows*" env-on))))
 ) ;;Stops putting {} on argumentless commands to "save" whitespace

#+END_SRC

Additionally, reftex code to recognize this environment as an equation
#+BEGIN_SRC elisp

(setq reftex-label-alist
      '(
        ("DispWithArrows*" ?e nil nil t)
        ("arrowEquation" ?e nil nil t)
        ))

#+END_SRC




* Smartparens Setup

global
#+BEGIN_SRC elisp

(require 'smartparens-config)
(require 'smartparens-latex)

(add-hook 'minibuffer-setup-hook 'turn-on-smartparens-strict-mode)

;;;;;;;;;;;;;;;;;;;;;;;;
;; keybinding management
(define-key smartparens-mode-map (kbd "C-M-f") 'sp-forward-sexp)
(define-key smartparens-mode-map (kbd "C-M-b") 'sp-backward-sexp)

(define-key smartparens-mode-map (kbd "C-M-d") 'sp-down-sexp)
(define-key smartparens-mode-map (kbd "C-M-a") 'sp-backward-down-sexp)
(define-key smartparens-mode-map (kbd "C-S-d") 'sp-beginning-of-sexp)
(define-key smartparens-mode-map (kbd "C-S-a") 'sp-end-of-sexp)

(define-key smartparens-mode-map (kbd "C-M-e") 'sp-up-sexp)
(define-key smartparens-mode-map (kbd "C-M-u") 'sp-backward-up-sexp)
(define-key smartparens-mode-map (kbd "C-M-t") 'sp-transpose-sexp)

(define-key smartparens-mode-map (kbd "C-M-n") 'sp-forward-hybrid-sexp)
(define-key smartparens-mode-map (kbd "C-M-p") 'sp-backward-hybrid-sexp)

(define-key smartparens-mode-map (kbd "C-M-k") 'sp-kill-sexp)
(define-key smartparens-mode-map (kbd "C-M-w") 'sp-rewrap-sexp)

(define-key smartparens-mode-map (kbd "M-<delete>") 'sp-unwrap-sexp)
(define-key smartparens-mode-map (kbd "M-<backspace>") 'sp-backward-unwrap-sexp)

(define-key smartparens-mode-map (kbd "C-<right>") 'sp-forward-slurp-sexp)
(define-key smartparens-mode-map (kbd "C-<left>") 'sp-forward-barf-sexp)
(define-key smartparens-mode-map (kbd "C-M-<left>") 'sp-backward-slurp-sexp)
(define-key smartparens-mode-map (kbd "C-M-<right>") 'sp-backward-barf-sexp)

(define-key smartparens-mode-map (kbd "M-D") 'sp-splice-sexp)
(define-key smartparens-mode-map (kbd "C-M-<delete>") 'sp-splice-sexp-killing-forward)
(define-key smartparens-mode-map (kbd "C-M-<backspace>") 'sp-splice-sexp-killing-backward)

(define-key smartparens-mode-map (kbd "C-]") 'sp-select-next-thing-exchange)
(define-key smartparens-mode-map (kbd "C-<left_bracket>") 'sp-select-previous-thing)
(define-key smartparens-mode-map (kbd "C-M-]") 'sp-select-next-thing)

(define-key smartparens-mode-map (kbd "M-F") 'sp-forward-symbol)
(define-key smartparens-mode-map (kbd "M-B") 'sp-backward-symbol)

(define-key smartparens-mode-map (kbd "C-\"") 'sp-change-inner)
(define-key smartparens-mode-map (kbd "M-i") 'sp-change-enclosing)
(sp-pair  "\\left(" "\\right)" :insert "M-p")
(sp-pair "(" ")" :wrap "S-C-8")
(sp-pair "[" "]" :insert "S-M-8")



(bind-key "C-M-s"
          (defhydra smartparens-hydra ()
            "smartparens"
            ("d" sp-down-sexp "Down")
            ("D" sp-backward-down-sexp "Backward-Down")
            ("u" sp-backward-up-sexp "Up")
            ("U" sp-up-sexp "Backward-Up")
            ("n" sp-next-sexp "Down")
            ("N" sp-previous-sexp "Down")
            ("c" sp-rewrap-sexp "Change Surround")
            ("<backspace>" sp-backward-unwrap-sexp "Delete Surround" :color red)
            ("h" sp-show-enclosing-pair "show")
            ("f" sp-forward-sexp "Forward")
            ("b" sp-backward-sexp "Backward")
            ("q" nil "Quit" :color blue))
          smartparens-mode-map)



;;;;;;;;;;;;;;;;;;
;; pair management

;;; tex-mode latex-mode
(sp-with-modes '(tex-mode plain-tex-mode latex-mode)
  (sp-local-tag "i" "\"<" "\">"))

#+END_SRC

