#+TITLE: Config
#+PROPERTY: header-args :tangle yes

#+BEGIN_SRC
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC

* Table of Contents
- [[#basics][Basics]]
  - [[#general][General]]
  - [[#line-numbering][Line Numbering]]
  - [[#theming][Theming]]
    - [[#transparency][Transparency]]
    - [[#font-stuff][Font Stuff]]
  - [[#org-mode][Org-Mode]]
    - [[#syntax-highlighting][Syntax Highlighting]]
- [[#company][Company]]
    - [[#org---latex-export-präambel][Org -> Latex Export Präambel]]
- [[#latex-setup][latex setup]]
- [[#smartparens-setup][Smartparens Setup]]


* Basics

** General

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.
#+BEGIN_SRC elisp

(setq user-full-name "John Doe"
      user-mail-address "john@doe.com")


(setq yas-snippet-dirs '("~/.emacs.d/snippets"))
      #+END_SRC

*** Which Key
Which Key Popup Time
#+BEGIN_SRC elisp

(after! which-key
  (setq which-key-idle-delay 0.1))

#+END_SRC

*** Poly Mode
Poly Mode
#+BEGIN_SRC elisp
                                        ;(after! ein:notebook-mode
                                        ;(setq poly-ein-mode t)
                                        ;)

(use-package! polymode)
(use-package! poly-markdown
  :config
  (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown-mode))
  )

(with-eval-after-load "markdown"
  (use-package poly-markdown))

(setq ein:polymode t)
(setq ein:completion-backend 'ein:use-company-backend)
#+END_SRC

*** Beacon Mode
Beacon Mode (Cursor blinking)
#+BEGIN_SRC elisp

(setq beacon-mode 1)

#+END_SRC

*** PDF Tools

#+BEGIN_SRC elisp

(after! pdf-view

  ;; open pdfs scaled to fit page
  (setq-default pdf-view-display-size 'fit-width)
  )
#+END_SRC



** Line Numbering

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC elisp
(setq display-line-numbers-type 'relative)
#+END_SRC

** Theming

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+BEGIN_SRC elisp

(setq doom-theme 'doom-dracula)
#+END_SRC


*** Transparency

#+BEGIN_SRC elisp

(set-frame-parameter (selected-frame) 'alpha '(100 100))

(add-to-list 'default-frame-alist '(alpha 100 100))
#+END_SRC

*** Font Stuff

Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

- `doom-font'
- `doom-variable-pitch-font'
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:

#+BEGIN_SRC elisp

(setq doom-font (font-spec :family "Iosevka" :size 22 :weight 'normal)
      doom-variable-pitch-font (font-spec :family "sans" :size 13))

#+END_SRC

** LSP Settings 

#+begin_src elisp
(setq lsp-ui-sideline-enable t
      lsp-enable-completion-at-point nil)


(after! rustic
  (setq rustic-format-on-save t)
  (setq rustic-lsp-server 'rust-analyzer))
#+end_src

*** LSP in Source Code Blocks Within Org Mode
#+begin_src elisp
(cl-defmacro lsp-org-babel-enable (lang)
  "Support LANG in org source code block."
  (setq centaur-lsp 'lsp-mode)
  (cl-check-type lang stringp)
  (let* ((edit-pre (intern (format "org-babel-edit-prep:%s" lang)))
         (intern-pre (intern (format "lsp--%s" (symbol-name edit-pre)))))
    `(progn
       (defun ,intern-pre (info)
         (let ((file-name (->> info caddr (alist-get :file))))
           (unless file-name
             (setq file-name (make-temp-file "babel-lsp-")))
           (setq buffer-file-name file-name)
           (lsp-deferred)))
       (put ',intern-pre 'function-documentation
            (format "Enable lsp-mode in the buffer of org source block (%s)."
                    (upcase ,lang)))
       (if (fboundp ',edit-pre)
           (advice-add ',edit-pre :after ',intern-pre)
         (progn
           (defun ,edit-pre (info)
             (,intern-pre info))
           (put ',edit-pre 'function-documentation
                (format "Prepare local buffer environment for org source block (%s)."
                        (upcase ,lang))))))))
(defvar org-babel-lang-list
  '("python" "jupyter" "bash" "sh"))
(dolist (lang org-babel-lang-list)
  (eval `(lsp-org-babel-enable ,lang)))
#+end_src

** Garbage Collection

#+begin_src elisp
(setq gc-cons-threshold 100000)
#+end_src



** Treemacs
#+BEGIN_SRC elisp

(setq treemacs--width-is-locked nil)
#+END_SRC


* Org-Mode

Org-Ref import
#+BEGIN_SRC elisp

(require 'org-ref)

#+END_SRC

If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!
#+BEGIN_SRC elisp

(setq org-directory "~/org/")

#+END_SRC

Changing bullet style
#+BEGIN_SRC elisp

(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))

#+END_SRC


Hide the emphasis markup (e.g. /.../ for italics, *...* for bold, etc.):
#+BEGIN_SRC elisp

(setq org-hide-emphasis-markers t)

#+END_SRC

List item marker
#+BEGIN_SRC elisp

(font-lock-add-keywords 'org-mode
                        '(("^ *\\([-]\\) "
                           (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

#+END_SRC


** Babel
#+BEGIN_SRC elisp
#+END_SRC


*** Syntax Highlighting

Fontify code in code blocks
#+BEGIN_SRC elisp

(setq org-src-fontify-natively t)

#+END_SRC



* Company


#+BEGIN_SRC elisp
#+END_SRC

*** Org -> Latex Export Präambel

My custom LaTeX class for Org-mode export. require is needed for it to work.
#+BEGIN_SRC elisp

(unless (boundp 'org-latex-classes)
  (setq org-latex-classes nil))

(add-to-list 'org-latex-classes
             '("myclass"
               "
                \\documentclass[12pt]{scrartcl}
                \\linespread{1.15}
[NO-DEFAULT-PACKAGES]
      [PACKAGES]
\\usepackage[ngerman]{babel}
\\usepackage[utf8]{inputenc}
\\usepackage{csquotes}
\\usepackage{amssymb,amsmath, amsthm, mathtools, mathrsfs}
\\usepackage{my_macros}
\\usepackage[backend= biber]{biblatex}

\\usepackage{scrlayer-scrpage}
\\ohead{Weber, Marcus}
\\ihead{Holzer, Yannik}


\\usepackage{float}
\\usepackage{caption}
\\captionsetup[figure]{labelfont={bf},name={Abbildung},labelsep=period}
\\captionsetup[table]{labelfont={bf},name={Tabelle},labelsep=period}
\\usepackage{hyperref}
\\usepackage{graphicx}
\\usepackage{geometry}
\\geometry{
 a4paper,
 left=25mm,
 right=25mm,
 top=25mm,
 bottom=20m}
\\usepackage{cleveref}
\\addto\\captionsngerman{
  \\crefname{figure}{Abb.}{Abb.}
  \\Crefname{figure}{Abbildung}{Abbildungen}
  \\crefname{table}{Tab.}{Tab.}
  \\crefname{equation}{Gl.}{Gl.}
\\setlength\\parindent{0pt}
\\usepackage{lmodern}
      [EXTRA]
\\linespread{1.1}
\\hypersetup{pdfborder=0 0 0}"
("\\section{%s}" . "\\section*{%s}")
("\\subsection{%s}" . "\\subsection*{%s}")
("\\subsubsection{%s}" . "\\subsubsection*{%s}")
("\\paragraph{%s}" . "\\paragraph*{%s}
                "
               )))

#+END_SRC


* latex setup

** Mixed Settings

#+BEGIN_SRC elisp

(setq tab-width 4
      LaTeX-item-indent 0 latex "latex"
      TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-view-program-list
      '(("PDF Tools" TeX-pdf-tools-sync-view)))
(add-hook
 'TeX-after-compilation-finished-hook
 #'TeX-revert-document-buffer)


(setq-default TeX-parse-self t)
(setq-default TeX-auto-save t)
(setq +latex-viewers '(pdf-tools))

(after! latex
  (setq TeX-save-query nil) ;; Save without asking when invoking TeX commands
  )
(after! tex
  (setq-hook! 'TeX-mode-hook +flyspell-immediately nil) ;; no flyspell check after opening the file
  )


#+END_SRC

** Smartparens LaTeX

#+begin_src elisp

(after! smartparens
  ;; Smartparens for whatever reason treats the insertion of dollar signs and quotes as single characters.
  (setq sp--special-self-insert-commands (delete `TeX-insert-dollar sp--special-self-insert-commands))
  (setq sp--special-self-insert-commands (delete `TeX-insert-quote sp--special-self-insert-commands)))
  #+END_SRC

Auto indent with RET (you don't need to constantly press TAB to get your indentation right).
#+BEGIN_SRC elisp

;;(add-hook 'TeX-mode-hook
;;         '(lambda () (local-set-key (kbd "RET") 'newline-and-indent)))

(add-hook 'LaTeX-mode-hook 'add-my-latex-environments)
(defun add-my-latex-environments ()
  (LaTeX-add-environments
   '("DispWithArrows*" LaTeX-env-label)
   '("arrowEquation" LaTeX-env-label)))
#+END_SRC


Code to make syntax highlighting work in Auctex
#+BEGIN_SRC elisp

(custom-set-variables
 '(font-latex-math-environments (quote
     ("display" "displaymath" "equation" "eqnarray" "gather" "multline"
      "align" "alignat" "xalignat" "dmath" "arrowEquation" "DispWithArrows*")))
 '(TeX-insert-braces nil)
 '(texmathp-tex-commands (quote (("arrowEquation" env-on) ("DispWithArrows*" env-on))))
 ) ;;Stops putting {} on argumentless commands to "save" whitespace

#+END_SRC

Additionally, reftex code to recognize this environment as an equation
#+BEGIN_SRC elisp

(setq reftex-label-alist
      '(
        ("DispWithArrows*" ?e nil nil t)
        ("arrowEquation" ?e nil nil t)
        ))

#+END_SRC




* Smartparens Setup

global
#+BEGIN_SRC elisp

(require 'smartparens-config)
(require 'smartparens-latex)

(add-hook 'minibuffer-setup-hook 'turn-on-smartparens-strict-mode)

;; -----------------------
;; keybinding management
;; -----------------------

(define-key smartparens-mode-map (kbd "C-<right>") 'sp-forward-slurp-sexp) ;; swallow first word after ()
(define-key smartparens-mode-map (kbd "C-<left>") 'sp-backward-slurp-sexp) ;; swallow first word before ()
(define-key smartparens-mode-map (kbd "C-M-<right>") 'sp-forward-barf-sexp) ;; push last word out of ()
(define-key smartparens-mode-map (kbd "C-M-<left>") 'sp-backward-barf-sexp) ;; push first word out of ()

(define-key smartparens-mode-map (kbd "C-M-l") 'sp-beginning-of-next-sexp)
(define-key smartparens-mode-map (kbd "C-M-h") 'sp-beginning-of-previous-sexp)
(define-key smartparens-mode-map (kbd "C-M-j") 'sp-down-sexp)
(define-key smartparens-mode-map (kbd "C-M-k") 'sp-backward-up-sexp)

(define-key smartparens-mode-map (kbd "C-l") 'sp-forward-symbol)
(define-key smartparens-mode-map (kbd "C-h") 'sp-backward-symbol)

(define-key smartparens-mode-map (kbd "M-L") 'sp-up-sexp)
(define-key smartparens-mode-map (kbd "M-H") 'sp-backward-up-sexp)
(define-key smartparens-mode-map (kbd "C-M-b") 'sp-beginning-of-sexp)
(define-key smartparens-mode-map (kbd "C-M-e") 'sp-end-of-sexp)

;;;;;;;;;;;;;;;;;;
;; pair management

;;; tex-mode latex-mode
(sp-with-modes '(tex-mode plain-tex-mode latex-mode)
  (sp-local-tag "i" "\"<" "\">"))
#+END_SRC

